@host = http://localhost:3000
###
@token = CbR7nl1Y1-ASDAL4sHO
###
@token-user = 8YbpkESaR-YGyjs83HM

###
@token-user2 = 4mHP8Pz2q-a6h8AWGSl

###
@token-user3 = 1smyLOTKS-Q_DuluBZU

###
@token-user4 = NyvwqMRRK-czTS2QGaX

###

POST {{host}}/api/users
Content-Type: application/json

  {
    "nombre": "Jose Luis",
    "apellido": "Villa Nueva",
    "correo": "JLVN@gmail.com",
    "password": "12345",
    "fecha": "1999-10-25",
    "sexo": "H"
  }

###

POST {{host}}/api/login
Content-Type: application/json

{
    "correo": "JLVN@gmail.com",
    "password": "12345"
}

###

GET  {{host}}/api/users
x-auth: {{token}}

###

GET  {{host}}/api/users?nombre=iego
x-auth: {{token-user}}

###

GET  {{host}}/api/users?apellido=eng
x-auth: {{token-user}}

###

GET  {{host}}/api/users?year=2021
x-auth: {{token-user}}

###
Get {{host}}/api/users?page=1
x-auth: {{token-user}}

###
Get {{host}}/api/users/JW@gmail.com
x-auth: {{token-user2}}

###
PUT {{host}}/api/users/CRomo@gmail.com
x-auth: {{token-user3}}
Content-Type: application/json

{
    "nombre": "Jose",
    "apellido": "Padilla",
    "correo": "1235@gmail.com",
    "password": "JKdsa",
    "fecha": "1990-01-25",
    "imagen": "https://randomuser.me/api/portraits/men/55.jpg",
    "sexo": "H"
  }

###
DELETE {{host}}/api/users/miguethegod@gmail.com
x-auth: {{token-user4}}